// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-available-donations.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.86.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-available-donations.ts
var list_available_donations_default = defineTool({
  name: "list_available_donations",
  title: "List available donations",
  description: "List food donations that are currently available to request.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max donations to return (default 20)."),
    search: z.string().optional().describe("Optional text to match against title, food type or pickup location.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("food_donations").select("id,title,description,food_type,quantity,serves_people,pickup_location,expiry_date,status,created_at").eq("status", "available").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (search?.trim()) {
      const term = `%${search.trim()}%`;
      query = query.or(
        `title.ilike.${term},food_type.ilike.${term},pickup_location.ilike.${term}`
      );
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { donations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-donation.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var create_donation_default = defineTool2({
  name: "create_donation",
  title: "Create donation",
  description: "Create a new food donation listing owned by the signed-in donor.",
  inputSchema: {
    title: z2.string().trim().min(1).describe("Short title of the donation."),
    description: z2.string().trim().min(1).describe("What the food is and its condition."),
    food_type: z2.string().trim().min(1).describe("Category, e.g. cooked meals, produce, bakery."),
    quantity: z2.string().trim().min(1).describe("Quantity description, e.g. '5 kg' or '20 meals'."),
    pickup_location: z2.string().trim().min(1).describe("Address or area for pickup."),
    expiry_date: z2.string().describe("Expiry / best-before date as an ISO date or timestamp."),
    serves_people: z2.number().int().positive().optional().describe("Approximate number of people served."),
    allergens: z2.array(z2.string()).optional().describe("Allergens present in the food."),
    dietary_info: z2.array(z2.string()).optional().describe("Dietary tags, e.g. vegetarian, halal.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("food_donations").insert({ ...input, donor_id: ctx.getUserId() }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { donation: data }
    };
  }
});

// src/lib/mcp/tools/request-donation.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var request_donation_default = defineTool3({
  name: "request_donation",
  title: "Request a donation",
  description: "Request an available food donation on behalf of the signed-in receiver.",
  inputSchema: {
    donation_id: z3.string().uuid().describe("ID of the donation to request."),
    message: z3.string().trim().optional().describe("Optional message to the donor.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ donation_id, message }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("donation_requests").insert({ donation_id, message: message ?? null, receiver_id: ctx.getUserId() }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { request: data }
    };
  }
});

// src/lib/mcp/tools/respond-to-request.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var respond_to_request_default = defineTool4({
  name: "respond_to_request",
  title: "Respond to a donation request",
  description: "Accept or reject a request made on one of the signed-in donor's donations.",
  inputSchema: {
    request_id: z4.string().uuid().describe("ID of the donation request."),
    decision: z4.enum(["accepted", "rejected"]).describe("Whether to accept or reject the request.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ request_id, decision }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("donation_requests").update({ status: decision, responded_at: (/* @__PURE__ */ new Date()).toISOString() }).eq("id", request_id).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return {
        content: [{ type: "text", text: "Request not found or you are not allowed to respond to it." }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { request: data }
    };
  }
});

// src/lib/mcp/tools/list-my-activity.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_my_activity_default = defineTool5({
  name: "list_my_activity",
  title: "List my donations and requests",
  description: "List the signed-in user's own food donations and donation requests, with their current status.",
  inputSchema: {
    limit: z5.number().int().min(1).max(50).optional().describe("Max rows per section (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const max = limit ?? 20;
    const [donations, requests] = await Promise.all([
      supabase.from("food_donations").select("id,title,food_type,quantity,status,expiry_date,pickup_location,created_at").eq("donor_id", userId).order("created_at", { ascending: false }).limit(max),
      supabase.from("donation_requests").select("id,donation_id,status,message,requested_at,responded_at,food_donations(title,pickup_location)").eq("receiver_id", userId).order("requested_at", { ascending: false }).limit(max)
    ]);
    const error = donations.error ?? requests.error;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const payload = { donations: donations.data ?? [], requests: requests.data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_my_profile_default = defineTool6({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Get the signed-in user's FoodShare profile, including their role (donor, receiver or delivery).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("id,full_name,email,phone,user_type,organization_name,address,bio").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No profile found for this account." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "raciqvtxwheracpvxavq";
var mcp_default = defineMcp({
  name: "foodshare-connect",
  title: "FoodShare Connect",
  version: "0.1.0",
  instructions: "Tools for FoodShare Connect, a surplus-food sharing app. Use `get_my_profile` to learn the signed-in user's role, `list_available_donations` to browse food that can be requested, `create_donation` for donors listing surplus food, `request_donation` for receivers claiming food, `respond_to_request` for donors accepting or rejecting requests, and `list_my_activity` to review the user's own donations and requests.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_my_profile_default,
    list_available_donations_default,
    list_my_activity_default,
    create_donation_default,
    request_donation_default,
    respond_to_request_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
